######################################################################
# Automatically generated by qmake (1.07a) Thu Jan 24 00:49:20 2008
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += main.cpp
